### ISSUE TITLE
Compare the memory consumption

### ISSUE THREAD

**Issue by kokizzu** [absolutelightning/treds#6]
it also nice to see

**Comment by absolutelightning** [comment]
Sure will do that. Thanks for mentioning this.

**Comment by absolutelightning** [comment]
Hey @kokizzu , For just the KV store, Treds takes less memory as compared to Redis for keys having `user:` as the common prefix. So I have put 10 Million Keys in Redis and Treds, each key starts with `user:` and is of pattern `user:%d` where the part after `:` is replaced by number from 1 to 10 Million.

Here is the screenshot of the memory by `htop` command

<img width="1512" alt="Screenshot 2024-09-28 at 9 28 02 PM" src="https://github.com/user-attachments/assets/8733039d-3291-4ed8-a64d-7e02d859b87a">
<img width="1512" alt="Screenshot 2024-09-28 at 9 26 39 PM" src="https://github.com/user-attachments/assets/50361081-65e1-41a5-a27e-11d93fb5894f">

Althought I am afraid the Sorted Maps store will take more memory as compared to Sorted Sets store in Redis.
